name: Share environment variables between steps

on:
  workflow_dispatch:

jobs:
  share-env-vars:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: HelloWorld

    steps:
      - name: Print env variable before setting it
        run: echo "MY_ENV_VAR before setting: $MY_ENV_VAR"

     - name: Set environment variable for next steps
        run: echo "MY_ENV_VAR=HelloWorldUpdated" >> $GITHUB_ENV

      - name: Print env variable after setting it
        run: echo "MY_ENV_VAR after setting: $MY_ENV_VAR"

